import type { FacilityResult } from "./types";

export const MOCK_RESULTS: FacilityResult[] = [
  {
    facility_id: "AIIMS-DEL-001",
    facility_name: "All India Institute of Medical Sciences",
    pin_code: "110029",
    state: "Delhi",
    city: "New Delhi",
    facility_type: "Government Tertiary Care",
    coordinates: { lat: 28.5672, long: 77.2100 },
    trust_score: 9,
    agent1_score: 8,
    validator_score: 9,
    interval_label: "8.0 – 9.5 / 10",
    interval_low: 8.0,
    interval_high: 9.5,
    mean_trust: 8.5,
    uncertainty: "High confidence — both agents agreed",
    validated: true,
    verified_capabilities: [
      "ICU 24x7", "Cardiac Cath Lab", "Trauma Centre Level 1",
      "Neurosurgery", "Dialysis", "Oncology", "NICU", "Blood Bank",
    ],
    truth_gap_notes: "Minor: staffing roster not published publicly for night shifts.",
    evidence_citations: [
      "[S1] AIIMS New Delhi operates a 2,500-bed tertiary care facility with 24x7 ICU and emergency services.",
      "[S2] The Cardiothoracic Centre is equipped with 4 cath labs and performs over 5,000 procedures annually.",
      "[S3] Trauma Centre is designated Level 1 and accepts referrals from across north India.",
    ],
    specialty_services: "All major specialties including cardiothoracic surgery, neurosurgery, organ transplant, and oncology.",
    equipment_status: "Latest generation MRI (3T), CT (256-slice), PET-CT, and 4 cardiac catheterisation labs operational.",
    staffing_levels: "Approx. 1,500 faculty and 3,000 resident doctors. Nurse-to-bed ratio 1:2 in ICU.",
    corrections: null,
    confidence_note: "High",
    query_match_notes: "Direct match on cardiac care query. Tertiary referral centre.",
    consistency_flag: null,
    is_medical_desert: false,
    desert_reason: null,
    crisis_score: 1.2,
    verified_capability_count: 8,
    rank_in_results: 1,
    recommendation: "Top recommendation for urgent cardiac care. Government facility with subsidised treatment and 24x7 emergency.",
    latency_ms: 8200,
  },
  {
    facility_id: "FOR-MUM-014",
    facility_name: "Fortis Hospital Mulund",
    pin_code: "400078",
    state: "Maharashtra",
    city: "Mumbai",
    facility_type: "Private Multi-specialty",
    coordinates: { lat: 19.1726, long: 72.9425 },
    trust_score: 6,
    agent1_score: 8,
    validator_score: 6,
    interval_label: "5.0 – 7.5 / 10",
    interval_low: 5.0,
    interval_high: 7.5,
    mean_trust: 6.25,
    uncertainty: "Moderate — validator reduced score after capability check",
    validated: false,
    verified_capabilities: ["ICU 24x7", "Cardiology OPD", "Dialysis", "Emergency"],
    truth_gap_notes: "[S2] mentions 'cardiac surgery available' but no evidence of in-house cath lab in last 3 quarters of public records.",
    evidence_citations: [
      "[S1] Fortis Mulund is a 300-bed multi-specialty hospital established in 2002.",
      "[S2] The hospital advertises cardiac surgery available, however the 2024 facility audit could not confirm an active cath lab.",
      "[S4] NABH accreditation valid through 2026.",
    ],
    specialty_services: "Cardiology (OPD only confirmed), General Surgery, Orthopaedics, Maternity.",
    equipment_status: "1.5T MRI, 64-slice CT operational. Cath lab status unverified.",
    staffing_levels: "12 ICU beds with dedicated intensivist coverage 18hrs/day.",
    corrections: "Agent 1 claimed full cardiac surgery capability. Validator reduced score: only OPD-level cardiology verifiable from cited sources.",
    confidence_note: "Medium",
    query_match_notes: "Partial match — cardiac care advertised but interventional capability unverified.",
    consistency_flag: null,
    is_medical_desert: false,
    desert_reason: null,
    crisis_score: 4.1,
    verified_capability_count: 4,
    rank_in_results: 2,
    recommendation: "Reasonable backup for stable cardiac patients. Confirm cath lab availability before transfer for STEMI/acute MI.",
    latency_ms: 8200,
  },
  {
    facility_id: "DH-BUL-077",
    facility_name: "District Hospital Bulandshahr",
    pin_code: "203001",
    state: "Uttar Pradesh",
    city: "Bulandshahr",
    facility_type: "Government District",
    coordinates: { lat: 28.4069, long: 77.8497 },
    trust_score: 5,
    agent1_score: 8,
    validator_score: 5,
    interval_label: "4.0 – 8.0 / 10",
    interval_low: 4.0,
    interval_high: 8.0,
    mean_trust: 6.5,
    uncertainty: "Low confidence — re-audit produced different score",
    validated: false,
    verified_capabilities: ["Emergency OPD", "Basic Pathology"],
    truth_gap_notes: "[S3] CMO report 2024: ICU has 8 beds but only 2 ventilators functional. No 24x7 cardiologist on roster.",
    evidence_citations: [
      "[S1] District Hospital Bulandshahr is the primary referral centre for the district.",
      "[S2] The hospital has ICU and ICCU as per the 2022 inauguration brochure.",
      "[S3] CMO inspection report (Mar 2024) noted 6 of 8 ventilators non-functional and shortage of trained ICU nurses.",
    ],
    specialty_services: "General medicine, paediatrics, basic surgery. No interventional cardiology.",
    equipment_status: "ECG, X-ray, basic ultrasound. ICU equipment partially functional per CMO audit.",
    staffing_levels: "Single MD Medicine on roster. No dedicated intensivist or cardiologist.",
    corrections: "Agent 1 accepted brochure claims of ICU/ICCU. Validator down-weighted using March 2024 CMO inspection findings.",
    confidence_note: "Low",
    query_match_notes: "Cardiac care query — facility lacks confirmed interventional capability.",
    consistency_flag: "Inconsistent — re-audit scored 3/10 vs original 8/10 (Δ5)",
    is_medical_desert: false,
    desert_reason: null,
    crisis_score: 6.8,
    verified_capability_count: 2,
    rank_in_results: 3,
    recommendation: "Stabilisation only. Refer urgently to AIIMS Delhi or Meerut Medical College for definitive cardiac care.",
    latency_ms: 8200,
  },
  {
    facility_id: "PHC-KOR-203",
    facility_name: "Primary Health Centre Koraput",
    pin_code: "764020",
    state: "Odisha",
    city: "Koraput",
    facility_type: "Primary Health Centre",
    coordinates: { lat: 18.8126, long: 82.7106 },
    trust_score: 2,
    agent1_score: 5,
    validator_score: 2,
    interval_label: "1.0 – 3.5 / 10",
    interval_low: 1.0,
    interval_high: 3.5,
    mean_trust: 2.25,
    uncertainty: "High confidence — both agents flagged as desert",
    validated: true,
    verified_capabilities: ["Outpatient consultation"],
    truth_gap_notes: "[S2] Listed services include emergency stabilisation, ICU referral pathway, and ambulance service. [S3] District audit: no functioning ambulance, ICU referral nearest 180km away.",
    evidence_citations: [
      "[S1] PHC Koraput serves a tribal population of approximately 45,000 across 27 villages.",
      "[S2] Listed services include emergency stabilisation, ICU referral pathway, and 24x7 ambulance service.",
      "[S3] District health bulletin Q4 2024: no functioning ambulance for last 9 months. Nearest ICU at Visakhapatnam, 180km.",
    ],
    specialty_services: "Outpatient general medicine only. No surgical or critical care capability.",
    equipment_status: "Basic diagnostic kit. No ECG. No oxygen concentrators reported functional.",
    staffing_levels: "1 MBBS doctor, 2 ANMs. No specialists.",
    corrections: "Agent 1 over-credited PHC for listed services. Validator confirmed only outpatient consultation is operationally available.",
    confidence_note: "High",
    query_match_notes: "Cardiac care query — facility cannot meaningfully serve.",
    consistency_flag: null,
    is_medical_desert: true,
    desert_reason: "3 capability fields claimed, 0 verified. Truth gaps: [S3] states no ambulance for 9 months, nearest ICU 180km away. Population 45,000 tribal residents have no realistic access to emergency cardiac care within the golden hour.",
    crisis_score: 9.4,
    verified_capability_count: 1,
    rank_in_results: 4,
    recommendation: "MEDICAL DESERT. Patient cannot be safely treated locally. Urgent: arrange private transport to Visakhapatnam (180km, ~4hr).",
    latency_ms: 8200,
  },
  {
    facility_id: "CHC-DUM-451",
    facility_name: "Community Health Centre Dumka",
    pin_code: "814101",
    state: "Jharkhand",
    city: "Dumka",
    facility_type: "Community Health Centre",
    coordinates: { lat: 24.2676, long: 87.2497 },
    trust_score: 3,
    agent1_score: 6,
    validator_score: 3,
    interval_label: "2.0 – 4.5 / 10",
    interval_low: 2.0,
    interval_high: 4.5,
    mean_trust: 3.25,
    uncertainty: "High confidence — capability gaps confirmed",
    validated: false,
    verified_capabilities: ["OPD", "Basic Lab"],
    truth_gap_notes: "[S1] CHC website lists 6-bed ICU; [S4] NHM dashboard shows ICU non-functional since 2023, equipment under repair.",
    evidence_citations: [
      "[S1] CHC Dumka website lists a 6-bed ICU established under PMSSY.",
      "[S2] Facility caters to santhal pargana sub-division, population 1.3 million.",
      "[S4] NHM facility dashboard (live): ICU status 'Non-functional — equipment under repair' since June 2023.",
    ],
    specialty_services: "General OPD, basic surgery (elective). No emergency cardiac capability.",
    equipment_status: "ICU equipment non-functional. ECG operational. No defibrillator on records.",
    staffing_levels: "3 MBBS doctors. No specialists. ICU staffing nil.",
    corrections: "Agent 1 accepted PMSSY ICU claim. Validator confirmed via NHM live dashboard that ICU has been non-functional 18+ months.",
    confidence_note: "Medium",
    query_match_notes: "Facility cannot meet cardiac emergency requirements.",
    consistency_flag: null,
    is_medical_desert: false,
    desert_reason: null,
    crisis_score: 8.1,
    verified_capability_count: 2,
    rank_in_results: 5,
    recommendation: "Not suitable for cardiac emergency. Refer to Tata Main Hospital Jamshedpur (200km) or Ranchi (250km).",
    latency_ms: 8200,
  },
];
